# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'QuizzGame' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for QuizzGame
  pod 'JellyGif'
  
  target 'QuizzGameTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'QuizzGameUITests' do
    # Pods for testing
  end

end
